### ISSUE TITLE
round keys

### ISSUE THREAD

**Issue by AjayDyavathi** [mikepound/feistel#4]
I think there's an issue with the round_keys

prekey is generated successfully from 0 -> 64
postkey is successful from -64 -> end
but
roundkeys are defined as
roundkeys = []
for i in range(10):
    temp = key_data[3 * half_block_size * i : 2 * half_block_size * i + half_block_size]
    # same as temp = key_data[3*32*i : 2*32*i + 32]
    roundkeys.append(temp)

I didn't understand what is happening here!
The above code doesn't produce 10 round keys, instead it produce only one for i = 0, and for the rest of iterations, the list slicing doesn't make sense.

Please kindly verify this section of code.

**Comment by mikepound** [comment]
This is a great spot! I've no idea how this bug got into the code - could have sworn I tested it :) I'm committing a fix shortly for this. Thanks 👍

**Comment by mikepound** [comment]
All done in commit 431112b, thanks!
